runtime: php81
env: standard

handlers:
  - url: /(.*\.(gif|png|jpg|css|js))$
    static_files: public/\1
    upload: public/.*\.(gif|png|jpg|css|js|svg|map)$
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto

beta_settings:
  cloud_sql_instances: /cloudsql/e5vsdosite:europe-central2:e5vosdo-db

env_variables:
  APP_NAME: e5vosdo.hu
  APP_ENV: production
  APP_KEY: base64:PTbZDh4IlTyJXDwJd2HXoclyVAUfKemBdfE72mV3WbU=
  APP_DEBUG: false
  DEBUGBAR_ENABLED: false
  APP_DOMAIN: e5vosdo.hu
  APP_URL: https://e5vosdo.hu
  FRONTEND_URL: https://e5vosdo.hu
  LOG_CHANNEL: stack
  LOG_DEPRECATIONS_CHANNEL: null
  LOG_LEVEL: debug

  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp

  MYSQL_ATTR_PERSISTENT: true
  DB_CONNECTION: mysql
  DB_HOST: 127.0.0.1
  DB_PORT: 3306
  DB_DATABASE: "data"
  DB_USERNAME: "root"
  DB_PASSWORD: "1234do67"
  DB_SOCKET: "/cloudsql/e5vsdosite:europe-central2:e5vosdo-db"

  BROADCAST_DRIVER: pusher
  CACHE_DRIVER: database
  FILESYSTEM_DISK: tmp
  QUEUE_CONNECTION: sync
  SESSION_DRIVER: array
  SESSION_LIFETIME: 120
  SESSION_DOMAIN: "e5vosdo.hu"
  SESSION_COOKIE: "e5vosdo.hu_session"
  SANCTUM_STATEFUIL_DOMAINS: https://e5vosdo.hu

  MEMCACHED_HOST: 127.0.0.1

  REDIS_HOST: 127.0.0.1
  REDIS_PASSWORD: null
  REDIS_PORT: 6379

  MAIL_MAILER: smtp
  MAIL_HOST: mailhog
  MAIL_PORT: 1025
  MAIL_USERNAME: null
  MAIL_PASSWORD: null
  MAIL_ENCRYPTION: null
  MAIL_FROM_ADDRESS: "hello@example.com"
  MAIL_FROM_NAME: "Eötvös DÖ"

  GOOGLE_CLIENT_ID: 352962433416-obdmdsbt2205mains21suujpvrfmhks4.apps.googleusercontent.com
  GOOGLE_CLIENT_SECRET: m3mp0-N9JlmRO-rluGVQy2BY
  GOOGLE_REDIRECT_URI: "https://e5vosdo.hu/auth/callback"

  APP_SERVICES_CACHE: /tmp/services.php
  APP_PACKAGES_CACHE: /tmp/packages.php
  APP_CONFIG_CACHE: /tmp/config.php
  APP_ROUTES_CACHE: /tmp/routes.php

  E5VOS_API_TOKEN: iiakmnn4huvaprvh3prrb2uukn26mjdc83i6yf3db686r282adijqeat5k5ide3cvgekvkrtmdq9hki754vp2xe7ikqyvmutb8d66yf64qjwq6qpy7bayi4kmcar455r
