name: Deploy to production
on:
  push:
    branches:
      - prod
  workflow_dispatch:
jobs:
  deploy:
    runs-on: "ubuntu-latest"
    environment: Elastic Beanstalk
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Exit if not prod
        run: |
          if [[ "${{ github.ref }}" != "refs/heads/prod" ]]; then
            echo "Branch is not prod, exiting."
            exit 0
          fi
      - name: Calculate version number
        id: vnum
        run: echo "version=$(sh ./ci/deployver.sh ${{github.run_id}})" > $GITHUB_OUTPUT
      - name: Print version number
        run: echo ${{steps.vnum.outputs.version}}
      - name: Install frontend dependencies
        run: npm ci
      - name: Install backend dependencies
        run: |
          composer install --prefer-dist --no-progress --no-ansi --no-interaction
          echo "${PWD}/vendor/bin" >> $GITHUB_PATH
      - name: Generate dotenv file
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_APP_NAME: e5vosdo.hu
          envkey_APP_ENV: production
          envkey_APP_KEY: ${{secrets.APP_KEY}}
          envkey_APP_DEBUG: false
          envkey_APP_DOMAIN: e5vosdo.hu
          envkey_APP_URL: "https://${APP_DOMAIN}"
          envkey_VITE_BACKEND: "${APP_URL}"
          envkey_LOG_CHANNEL: stack
          envkey_LOG_DEPRECATIONS_CHANNEL: "null"
          envkey_LOG_LEVEL: error

          envkey_DB_CONNECTION: mysql
          envkey_DB_HOST: ${{secrets.DB_HOST}}
          envkey_DB_PORT: ${{secrets.DB_PORT}}
          envkey_DB_DATABASE: ${{secrets.DB_DATABASE}}
          envkey_DB_USERNAME: ${{secrets.DB_USERNAME}}
          envkey_DB_PASSWORD: ${{secrets.DB_PASSWORD}}
          envkey_MYSQL_ATTR_SSL_CA: /etc/pki/tls/certs/ca-bundle.crt

          envkey_BROADCAST_DRIVER: pusher
          envkey_CACHE_DRIVER: database
          envkey_FILESYSTEM_DISK: local
          envkey_QUEUE_CONNECTION: sync
          envkey_SESSION_DRIVER: file
          envkey_SESSION_LIFETIME: 120
          envkey_SESSION_DOMAIN: "${APP_DOMAIN}"
          envkey_SESSION_COOKIE: "${APP_NAME}_session"
          envkey_SANCTUM_STATEFUIL_DOMAINS: "${APP_URL}"

          envkey_MEMCACHED_HOST: 127.0.0.1

          envkey_REDIS_HOST: 127.0.0.1
          envkey_REDIS_PASSWORD: "null"
          envkey_REDIS_PORT: 6379

          envkey_MAIL_MAILER: smtp
          envkey_MAIL_HOST: mailhog
          envkey_MAIL_PORT: 1025
          envkey_MAIL_USERNAME: "null"
          envkey_MAIL_PASSWORD: "null"
          envkey_MAIL_ENCRYPTION: "null"
          envkey_MAIL_FROM_ADDRESS: do@e5vos.hu
          envkey_MAIL_FROM_NAME: "${APP_NAME}"

          envkey_AWS_ACCESS_KEY_ID: ""
          envkey_AWS_SECRET_ACCESS_KEY: ""
          envkey_AWS_DEFAULT_REGION: ${{vars.AWS_REGION}}
          envkey_AWS_BUCKET: ""
          envkey_AWS_USE_PATH_STYLE_ENDPOINT: false

          envkey_PUSHER_APP_ID: ""
          envkey_PUSHER_APP_KEY: ""
          envkey_PUSHER_APP_SECRET: ""
          envkey_PUSHER_HOST: ""
          envkey_PUSHER_PORT: 443
          envkey_PUSHER_SCHEME: https
          envkey_PUSHER_APP_CLUSTER: mt1

          envkey_VITE_PUSHER_APP_KEY: "${PUSHER_APP_KEY}"
          envkey_VITE_PUSHER_HOST: "${PUSHER_HOST}"
          envkey_VITE_PUSHER_PORT: "${PUSHER_PORT}"
          envkey_VITE_PUSHER_SCHEME: "${PUSHER_SCHEME}"
          envkey_VITE_PUSHER_APP_CLUSTER: "${PUSHER_APP_CLUSTER}"

          envkey_GOOGLE_CLIENT_ID: "${{secrets.GOOGLE_CLIENT_ID}}"
          envkey_GOOGLE_CLIENT_SECRET: "${{secrets.GOOGLE_CLIENT_SECRET}}"
          envkey_GOOGLE_REDIRECT_URI: "${APP_URL}/auth/callback"

          envkey_E5VOS_API_TOKEN: "${{secrets.E5VOS_API_TOKEN}}"
          envkey_E5VOS_API_URL: "${{vars.E5VOS_API_URL}}"
          envkey_E5VOS_FAKE_API: false

          envkey_DEBUG_API_KEY: "${{secrets.DEBUG_API_KEY}}"
          envkey_DISCORD_WEBHOOK: "${{secrets.DISCORD_WEBHOOK}}"

          envkey_VITE_EVENT_HU_SHORT: "GL"
          envkey_VITE_EVENT_EN_SHORT: "FV"
          envkey_VITE_EVENT_HU: "Gyárlátogatás"
          envkey_VITE_EVENT_EN: "\"Factory Visit \""

      - name: Generate Routes
        run: php artisan ziggy:generate --types

      - name: Build frontend
        run: npm run build

      - name: Zip files
        run: sh ./ci/zip.sh deploy_${{steps.vnum.outputs.version}}.zip

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          region: ${{vars.AWS_REGION}}
          application_name: ${{vars.EB_APP_NAME}}
          environment_name: ${{vars.EB_ENV_NAME}}
          version_label: ${{steps.vnum.outputs.version}}
          version_description: ${{github.SHA}}
          deployment_package: deploy_${{steps.vnum.outputs.version}}.zip
          aws_access_key: ${{secrets.AWS_DEPLOY_ACCESS_KEY_ID}}
          aws_secret_key: ${{secrets.AWS_DEPLOY_SECRET_ACCESS_KEY}}
          wait_for_deployment: true
